apiVersion: v1
kind: Service
metadata:
  name: beta
  namespace: pulsar
  labels:
    app: pulsar
    component: broker
spec:
  ports:
    - port: 8080
      name: http
    - port: 6650
      name: pulsar
  clusterIP: None
  selector:
    app: pulsar
    component: broker
    cluster: beta
---
apiVersion: v1
kind: Pod
metadata:
  name: beta
  namespace: pulsar
  labels:
    app: pulsar
    component: broker
    cluster: beta
spec:
  containers:
    - name: broker
      image: apachepulsar/pulsar-all:2.10.0
      command: ["sh", "-c", "bin/apply-config-from-env.py conf/standalone.conf && bin/gen-yml-from-env.py conf/functions_worker.yml && bin/pulsar standalone -nss -nfw"]
      ports:
        - containerPort: 8080
        - containerPort: 6650
      readinessProbe:
        httpGet:
          path: /admin/v2/brokers/health
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /admin/v2/brokers/health
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 30
      envFrom:
        - configMapRef:
            name: broker-config
      env:
        - name: advertisedAddress
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: clusterName
          value: beta
        - name: PF_pulsarFunctionsCluster
          value: beta
      volumeMounts:
        - mountPath: /pulsar/data
          name: data-volume
  volumes:
    - name: data-volume
      emptyDir: {}
